language: node_js

node_js:
  - lts/*

services:
  - docker
  - mongodb

cache:
  directories:
    - node_modules

before_script:
  - sleep 15 # Artificial delay to allow MongoDB to prepare.

script:
  - npm test

before_deploy:
  - docker logout
  - docker login -u "$HEROKU_UNAME" -p "$HEROKU_API_KEY" registry.heroku.com
  - travis_wait docker build -t quicknote .
  - docker images
  - docker tag quicknote registry.heroku.com/quicknote

deploy:
  provider: script
  script: docker push registry.heroku.com/quicknote
  on:
    branch: master

after_deploy:
  docker logout
