language: node_js

node_js:
  - lts/*

services:
  - docker
  - mongodb

cache:
  directories:
    - node_modules

before_script:
  - sleep 15 # Artificial delay to allow MongoDB to prepare.

script:
  - npm test

before_deploy:
  - docker login
  - echo "$DH_PWORD" | docker login -u "$DH_UNAME"
  - travis_wait docker build -t quicknote .
  - docker images
  - docker tag quicknote $DH_UNAME/quicknote

deploy:
  provider: script
  script: docker push $DH_UNAME/quicknote
  on:
    branch: master

after_deploy:
  docker logout
