language: node_js

node_js:
  - lts/*

services:
  - docker
  - mongodb

cache:
  directories:
    - node_modules

before_script: # Artificial delay to allow MongoDB to prepare.
  - sleep 15

script:
  - npm test

before_deploy:
  - echo "$DH_PWORD" | docker login -u "$DH_UNAME" --password-stdin
  - docker build -t quicknote .
  - docker images
  - docker tag quicknote $DH_UNAME/quicknote

deploy:
  provider: script
  script: docker push $DH_UNAME/quicknote
  on:
    branch: master
